// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA317XPD381I9l5-sb68FdtLmA_InjsVls',
    appId: '1:69940964928:web:1ad98b0e70df3c44d4b9a5',
    messagingSenderId: '69940964928',
    projectId: 'expense-manager-2d08e',
    authDomain: 'expense-manager-2d08e.firebaseapp.com',
    storageBucket: 'expense-manager-2d08e.firebasestorage.app',
    measurementId: 'G-NPCPSBC77K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCF4M2Pg6Yxw_p2Pv4q-MWHRG-MFSXs9mc',
    appId: '1:69940964928:android:1e49be1c1a2c155cd4b9a5',
    messagingSenderId: '69940964928',
    projectId: 'expense-manager-2d08e',
    storageBucket: 'expense-manager-2d08e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu9evONy0sAfzC0DW1Xvmo8lPNjR46f9A',
    appId: '1:69940964928:ios:73cd25cfb09a5be6d4b9a5',
    messagingSenderId: '69940964928',
    projectId: 'expense-manager-2d08e',
    storageBucket: 'expense-manager-2d08e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu9evONy0sAfzC0DW1Xvmo8lPNjR46f9A',
    appId: '1:69940964928:ios:73cd25cfb09a5be6d4b9a5',
    messagingSenderId: '69940964928',
    projectId: 'expense-manager-2d08e',
    storageBucket: 'expense-manager-2d08e.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA317XPD381I9l5-sb68FdtLmA_InjsVls',
    appId: '1:69940964928:web:1777fc1e879cf7a9d4b9a5',
    messagingSenderId: '69940964928',
    projectId: 'expense-manager-2d08e',
    authDomain: 'expense-manager-2d08e.firebaseapp.com',
    storageBucket: 'expense-manager-2d08e.firebasestorage.app',
    measurementId: 'G-YK2EEGRZBL',
  );
}
